[workspace]
resolver = "2"
members = [
    "crates/directx-shader-translate",
    "crates/directx-graphics-vulkan",
    "crates/directx-graphics-window",
]

[workspace.package]
version      = "0.1.0"
edition      = "2021"
authors      = ["aon-co-jp"]
license      = "MIT"
repository   = "https://github.com/aon-co-jp/open-directx"
